# Generated by Django 5.2.6 on 2025-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="страна"
            ),
        ),
    ]
