# Generated by Django 5.2.6 on 2025-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
