# Generated by Django 5.2.4 on 2025-10-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="users/", verbose_name="аватарка"
            ),
        ),
    ]
