# Generated by Django 5.2.6 on 2025-10-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing",
            "0002_alter_mailingattempt_options_alter_mailing_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [("view_all_clients", "Can view all clients")],
                "verbose_name": "получатель рассылки",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("set_status", "Can change the status of the mailing"),
                    ("view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Can view all messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
