# Generated by Django 5.2.6 on 2025-10-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "verbose_name": "получатель рассылки",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={"verbose_name": "рассылка", "verbose_name_plural": "рассылки"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "сообщение", "verbose_name_plural": "сообщения"},
        ),
    ]
