# Generated by Django 5.2.6 on 2025-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="recipient",
            field=models.CharField(default=" ", max_length=255),
            preserve_default=False,
        ),
    ]
